### ISSUE TITLE
Display has odd warm tint.

### ISSUE THREAD

**Issue by AM4Ryzen** [hockeymikey/android_device_sony_lilac#59]
I normally use my phones somewhere above 6000K, but below 8000K, because it matches or is similar enough to my other displays that I don't really notice, however with this ROM, I have to max it out to 10000K for it to be close, and it can still have a warmer tint compared to other phones and displays that I have.

**Comment by hockeymikey** [comment]
So LiveDisplay is set to automatic in these cases?

**Comment by AM4Ryzen** [comment]
> So LiveDisplay is set to automatic in these cases?

I set it to the day setting only and tweak the color temperature to the values I sent above. Turning it fully off, even on a normal phone, makes the display a bit warm.

**Comment by hockeymikey** [comment]
> > So LiveDisplay is set to automatic in these cases?
> 
> I set it to the day setting only and tweak the color temperature to the values I sent above. Turning it fully off, even on a normal phone, makes the display a bit warm.

I really don't think so, I think 10k looks too cool (blue). I think the setting when off is just perfect. It looks alittle too warm when you're on blue for way too long, but on it's own it looks fine. I compared against my stock xz2c, it looks fine. The xz1c colors don't look as rich though, but I think that's as expected.

**Comment by hockeymikey** [comment]
If others can chime in to it otherwise I'm going to leave it as be. Or if stock looks vastly different.
