### ISSUE TITLE
Volume down button sometimes doesn't work, requires reboot to fix.

### ISSUE THREAD

**Issue by AM4Ryzen** [hockeymikey/android_device_sony_lilac#71]
I don't think this is a hardware issue due to the fact that it works again after rebooting.

**Comment by hockeymikey** [comment]
When do you see this happening? I never experienced this before.

**Comment by AM4Ryzen** [comment]
> When do you see this happening? I never experienced this before.

After using the phone for a while. If I remember, I'll record a video of it.

**Comment by hockeymikey** [comment]
Yeah try to get some logs and think of what apps you use and if there is a pattern. I have never had this happen to me before.

**Comment by AM4Ryzen** [comment]
Appears to actually be a hardware issue, guess I won't be able to test any potential newer releases of the ROM unless OTA is able to work on current build.

**Comment by hockeymikey** [comment]
That sucks. Does it appear all the time then for you? I mean we can figure something out. It might fix itself too.

**Comment by AM4Ryzen** [comment]
> 
> 
> That sucks. Does it appear all the time then for you? I mean we can figure something out. It might fix itself too.

Yes, and the volume up button broke too.
