### ISSUE TITLE
Ringtone and notification volumes unable to be unlinked

### ISSUE THREAD

**Issue by AM4Ryzen** [hockeymikey/android_device_sony_lilac#72]
When unlinked, the volumes are still linked, but I can increase both sliders instead of just the ringer.

**Comment by hockeymikey** [comment]
Unlinked?

**Comment by AM4Ryzen** [comment]
> 
> 
> Unlinked?

Yeah, I recorded a video but Android is being pissy.

**Comment by hockeymikey** [comment]
Hmmmm should they be unlinked?

**Comment by AM4Ryzen** [comment]
> Hmmmm should they be unlinked?

Was wanting to unlink them so that I can hear phone calls but notifications only vibrate. Also I'm finally able to attach that video.
https://user-images.githubusercontent.com/39643236/137236918-d47c68bc-ac4f-477f-b90e-86a2f04c5648.mp4

**Comment by hockeymikey** [comment]
Hmm, makes sense. Kinda seems like a bug then testing on my other xz2c

**Comment by AM4Ryzen** [comment]
> Hmm, makes sense. Kinda seems like a bug then testing on my other xz2c

You ported this to the XZ2C?

**Comment by hockeymikey** [comment]
> > Hmm, makes sense. Kinda seems like a bug then testing on my other xz2c
> 
> You ported this to the XZ2C?

No, just using stock on there. I would like to port to other phones eventually when I get more features into the rom.

**Comment by hockeymikey** [comment]
This is a setting under Sounds which you can toggle off.

**Comment by hockeymikey** [comment]
![Screenshot_20211224-224312_Settings](https://user-images.githubusercontent.com/1435185/147377576-fd3db85e-7d2d-47ca-979d-e88d4d4b96ce.png)

**Comment by AM4Ryzen** [comment]
> This is a setting under Sounds which you can toggle off.

Watch the video I sent a while back.

**Comment by hockeymikey** [comment]
Ya that's just bugged for you. Works fine for both of my devices. Maybe using the wrong firmware is your issue?

**Comment by AM4Ryzen** [comment]
Well, I finally went to the firmware you sent. Split screen works now, I can adjust these volumes differently but it still kinda jank, the ROM is better now that I've used the proper firmware.

Also apparently my Type C port is flakey, I had to not touch my phone while flashing, and apparently two different systems saw it as a USB 1.1 device, so flashing was very slow.

**Comment by hockeymikey** [comment]
That's amazing to hear! Glad it's working better. Ya, the notifications can be jank like if I want vibrate ring and notification sounds, which doesn't make sense but should maybe still be possible. 
That's too bad. Maybe try blowing it out, maybe it has some dirt in it?

**Comment by AM4Ryzen** [comment]
> Maybe try blowing it out, maybe it has some dirt in it?

I think it's more than just dirt. The headphone jack was similar, I had to scrub it with an isopropyl soaked cotton swab and insert and remove the plug a few times for it to be reliableish.

**Comment by hockeymikey** [comment]
Crazy it can get so dirty.
